(defpackage :key
  (:use :cl))

(in-package :key)

(defconstant ctrl-space 0)
(defconstant ctrl-a 1)
(defconstant ctrl-b 2)
(defconstant ctrl-c 3)
(defconstant ctrl-d 4)
(defconstant ctrl-e 5)
(defconstant ctrl-f 6)
(defconstant ctrl-g 7)
(defconstant ctrl-h 8)
(defconstant ctrl-i 9)
(defconstant ctrl-j 10)
(defconstant ctrl-k 11)
(defconstant ctrl-l 12)
(defconstant ctrl-m 13)
(defconstant ctrl-n 14)
(defconstant ctrl-o 15)
(defconstant ctrl-p 16)
(defconstant ctrl-q 17)
(defconstant ctrl-r 18)
(defconstant ctrl-s 19)
(defconstant ctrl-t 20)
(defconstant ctrl-u 21)
(defconstant ctrl-v 22)
(defconstant ctrl-w 23)
(defconstant ctrl-x 24)
(defconstant ctrl-y 25)
(defconstant ctrl-z 26)
(defconstant escape 27)
