(defpackage :key
  (:use :cl))

(in-package :key)

(defconstant ctrl-space (code-char 0))
(defconstant ctrl-a (code-char 1))
(defconstant ctrl-b (code-char 2))
(defconstant ctrl-c (code-char 3))
(defconstant ctrl-d (code-char 4))
(defconstant ctrl-e (code-char 5))
(defconstant ctrl-f (code-char 6))
(defconstant ctrl-g (code-char 7))
(defconstant ctrl-h (code-char 8))
(defconstant ctrl-i (code-char 9))
(defconstant ctrl-j (code-char 10))
(defconstant ctrl-k (code-char 11))
(defconstant ctrl-l (code-char 12))
(defconstant ctrl-m (code-char 13))
(defconstant ctrl-n (code-char 14))
(defconstant ctrl-o (code-char 15))
(defconstant ctrl-p (code-char 16))
(defconstant ctrl-q (code-char 17))
(defconstant ctrl-r (code-char 18))
(defconstant ctrl-s (code-char 19))
(defconstant ctrl-t (code-char 20))
(defconstant ctrl-u (code-char 21))
(defconstant ctrl-v (code-char 22))
(defconstant ctrl-w (code-char 23))
(defconstant ctrl-x (code-char 24))
(defconstant ctrl-y (code-char 25))
(defconstant ctrl-z (code-char 26))
(defconstant escape (code-char 27))
