(in-package :lem)

(define-key *global-keymap* "C-x#" 'filter-buffer)
(defcommand filter-buffer (str) ("sFilter buffer: ")
  (let ((outstr (make-array '(0)
                  :element-type 'character
                  :fill-pointer t)))
    (with-output-to-string (output outstr)
      (let ((temp-file-name (temp-file-name)))
        (write-to-file (window-buffer) temp-file-name)
        (shell-command (format nil "cat ~a | ~a" temp-file-name str)
          :output output)
        (delete-file temp-file-name)))
    (erase-buffer)
    (insert-string outstr)
    (beginning-of-buffer)))
