(defpackage :lem-vi-mode/tests/visual
  (:use :cl
        :lem
        :rove
        :lem-vi-mode/tests/utils)
  (:import-from :lem/common/timer
                :with-timer-manager)
  (:import-from :lem-core
                :lem-timer-manager)
  (:import-from :lem-fake-interface
                :with-fake-interface)
  (:import-from :named-readtables
                :in-readtable))
(in-package :lem-vi-mode/tests/visual)

(in-readtable :interpol-syntax)

(deftest visual-switch
  (with-timer-manager (make-instance 'lem-timer-manager)
    (with-fake-interface ()
      (with-vi-buffer (#?"[a]bc\ndef\n")
        (cmd "v")
        (ok (buf= #?"<[a]>bc\ndef\n"))
        (cmd "l")
        (ok (buf= #?"<a[b]>c\ndef\n"))
        (cmd "v")
        (ok (buf= #?"a[b]c\ndef\n"))
        (cmd "v")
        (ok (buf= #?"a<[b]>c\ndef\n"))
        (cmd "V")
        (ok (buf= #?"<a[b]c>\ndef\n"))
        (cmd "j")
        (ok (buf= #?"<abc\nd[e]f>\n"))
        (cmd "l<C-v>")
        (ok (buf= #?"a<bc>\nd<e[f]>\n"))
        (cmd "v")
        (ok (buf= #?"a<bc\nde[f]>\n"))
        (cmd "v")
        (ok (buf= #?"abc\nde[f]\n"))))))

(deftest text-objects
  (with-timer-manager (make-instance 'lem-timer-manager)
    (with-fake-interface ()
      (testing "vaw"
        (with-vi-buffer (#?"  [ ]foo bar   baz  \n")
          (cmd "vaw")
          (ok (buf= #?"<   fo[o]> bar   baz  \n")))
        (with-vi-buffer (#?" < [ ]> foo bar   baz  \n")
          (cmd "aw")
          (ok (buf= #?" <   fo[o]> bar   baz  \n")))
        (with-vi-buffer (#?" < [ ]>foo bar   baz  \n")
          (cmd "aw")
          (ok (buf= #?" <  foo[ ]>bar   baz  \n")))
        (with-vi-buffer (#?" <[ ] > foo bar   baz  \n")
          (cmd "aw")
          (ok (buf= #?"<[ ]  > foo bar   baz  \n")))
        (with-vi-buffer (#?" f[o]o bar \n")
          (cmd "vaw")
          (ok (buf= #?" <foo[ ]>bar \n")))
        (with-vi-buffer (#?" f[o]o bar \n")
          (cmd "v2aw")
          (ok (buf= #?" <foo bar[ ]>\n")))
        (with-vi-buffer (#?" f[o]o bar \n")
          (cmd "v3aw")
          (ok (buf= #?" <foo bar [\n]>")))
        (with-vi-buffer (#?" foo b[a]r \n")
          (cmd "Vaw")
          (ok (buf= #?" foo <bar[ ]>\n")))
        (with-vi-buffer (#?" foo b[a]r\n")
          (cmd "vaw")
          (ok (buf= #?" foo< ba[r]>\n"))))
      (testing "viw"
        (with-vi-buffer (#?" [ ] foo bar\n")
          (cmd "viw")
          (ok (buf= #?"<  [ ]>foo bar\n")))
        (with-vi-buffer (#?"f[o]o bar\n")
          (cmd "viw")
          (ok (buf= #?"<fo[o]> bar\n")))
        (with-vi-buffer (#?"f[o]o bar\n")
          (cmd "v3iw")
          (ok (buf= #?"<foo ba[r]>\n")))))))
