#!/bin/sh

frontend=ncurses

case $1 in
	--frontend|-f)
		frontend=$2
		shift 2
	;;
esac

__which(){
    command -v "$1" 2> /dev/null
}

if __which lem-$frontend > /dev/null;then
    lem-$frontend $*
else
    echo "unknown frontend: $frontend"
fi
