#!/bin/sh

frontend=${LEM_DEFAULT_FRONTEND:-ncurses}
cwd=`dirname $0`

case $1 in
	--frontend|-f)
		frontend=$2
		shift 2
	;;
esac

__which() {
    [ -f $cwd/$1 ] || command -v "$1" 2> /dev/null
}

if __which lem-$frontend > /dev/null;then
    [ -f $cwd/lem-$frontend ] && exec $cwd/lem-$frontend "$@"
    exec lem-$frontend "$@"
else
    echo "unknown frontend: $frontend"
fi
