# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  async-process = {
    pname = "async-process";
    version = "725da0ab1c21a29cc02e283236a2c2e88947fa65";
    src = fetchgit {
      url = "https://github.com/lem-project/async-process";
      rev = "725da0ab1c21a29cc02e283236a2c2e88947fa65";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CRK4BDooxTts9b4Hvl15zqvHYPDA6yovHEE0Dr0nod4=";
    };
    date = "2025-12-10";
  };
  jsonrpc = {
    pname = "jsonrpc";
    version = "42fa96ec34f6b6be77a6f12f7c4e84f375eff019";
    src = fetchgit {
      url = "https://github.com/cxxxr/jsonrpc";
      rev = "42fa96ec34f6b6be77a6f12f7c4e84f375eff019";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tG2poXDvHX6twLmW8keaJedKfrFpmoHJZAmyuN0NRFk=";
    };
    date = "2025-08-04";
  };
  lem-mailbox = {
    pname = "lem-mailbox";
    version = "12d629541da440fadf771b0225a051ae65fa342a";
    src = fetchgit {
      url = "https://github.com/lem-project/lem-mailbox";
      rev = "12d629541da440fadf771b0225a051ae65fa342a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hb6GSWA7vUuvSSPSmfZ80aBuvSVyg74qveoCPRP2CeI=";
    };
    date = "2023-09-10";
  };
  micros = {
    pname = "micros";
    version = "e1d3857400a9bf7d1c6c2852d9c7017a0dc52217";
    src = fetchgit {
      url = "https://github.com/lem-project/micros";
      rev = "e1d3857400a9bf7d1c6c2852d9c7017a0dc52217";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NryjqfihHjRo4thBLmdeIaZuCNBFFWVDze55KD6nxrY=";
    };
    date = "2025-08-13";
  };
  webview = {
    pname = "webview";
    version = "238a0be10c6c37311ce2587ef99142f65abd880a";
    src = fetchgit {
      url = "https://github.com/lem-project/webview.git";
      rev = "238a0be10c6c37311ce2587ef99142f65abd880a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PsHF4PoSa93x2vHrqU1aeNHKutli6Y//Yqs5SQGxGWU=";
    };
    date = "2025-08-23";
  };
}
