# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  async-process = {
    pname = "async-process";
    version = "3ea46fcd238fdda101b644221ecf5e311c171a21";
    src = fetchgit {
      url = "https://github.com/lem-project/async-process";
      rev = "3ea46fcd238fdda101b644221ecf5e311c171a21";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2qBjZ7ruhz6zmhkQBOkIQ/4eKH1Nvzfr5Gsa+0P8OFA=";
    };
    date = "2025-12-16";
  };
  jsonrpc = {
    pname = "jsonrpc";
    version = "42fa96ec34f6b6be77a6f12f7c4e84f375eff019";
    src = fetchgit {
      url = "https://github.com/cxxxr/jsonrpc";
      rev = "42fa96ec34f6b6be77a6f12f7c4e84f375eff019";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tG2poXDvHX6twLmW8keaJedKfrFpmoHJZAmyuN0NRFk=";
    };
    date = "2025-08-04";
  };
  lem-mailbox = {
    pname = "lem-mailbox";
    version = "12d629541da440fadf771b0225a051ae65fa342a";
    src = fetchgit {
      url = "https://github.com/lem-project/lem-mailbox";
      rev = "12d629541da440fadf771b0225a051ae65fa342a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hb6GSWA7vUuvSSPSmfZ80aBuvSVyg74qveoCPRP2CeI=";
    };
    date = "2023-09-10";
  };
  micros = {
    pname = "micros";
    version = "da575de07240c37fd7f6586feb95e30cc569e92f";
    src = fetchgit {
      url = "https://github.com/lem-project/micros";
      rev = "da575de07240c37fd7f6586feb95e30cc569e92f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JBGMVDEfbH96ag3OlnU49hpit9xydFQP4y8H08W/D4g=";
    };
    date = "2025-12-17";
  };
  webview = {
    pname = "webview";
    version = "238a0be10c6c37311ce2587ef99142f65abd880a";
    src = fetchgit {
      url = "https://github.com/lem-project/webview.git";
      rev = "238a0be10c6c37311ce2587ef99142f65abd880a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PsHF4PoSa93x2vHrqU1aeNHKutli6Y//Yqs5SQGxGWU=";
    };
    date = "2025-08-23";
  };
  webview-upstream = {
    pname = "webview-upstream";
    version = "0.12.0";
    src = fetchFromGitHub {
      owner = "webview";
      repo = "webview";
      rev = "0.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-pmqodl2fIlCNJTZz1U5spW4MpcoMhQt5WFh3+TRny3U=";
    };
  };
}
