# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  async-process = {
    pname = "async-process";
    version = "239f5f10d230a19d052b88b5440e9325dfc4c5a8";
    src = fetchgit {
      url = "https://github.com/lem-project/async-process";
      rev = "239f5f10d230a19d052b88b5440e9325dfc4c5a8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UFNjj4UKmCC1bCqqfFTZQ0hY8FXm5kAeMFr/4YLd/hg=";
    };
    date = "2025-11-24";
  };
  jsonrpc = {
    pname = "jsonrpc";
    version = "42fa96ec34f6b6be77a6f12f7c4e84f375eff019";
    src = fetchgit {
      url = "https://github.com/cxxxr/jsonrpc";
      rev = "42fa96ec34f6b6be77a6f12f7c4e84f375eff019";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tG2poXDvHX6twLmW8keaJedKfrFpmoHJZAmyuN0NRFk=";
    };
    date = "2025-08-04";
  };
  lem-mailbox = {
    pname = "lem-mailbox";
    version = "12d629541da440fadf771b0225a051ae65fa342a";
    src = fetchgit {
      url = "https://github.com/lem-project/lem-mailbox";
      rev = "12d629541da440fadf771b0225a051ae65fa342a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hb6GSWA7vUuvSSPSmfZ80aBuvSVyg74qveoCPRP2CeI=";
    };
    date = "2023-09-10";
  };
  micros = {
    pname = "micros";
    version = "e1d3857400a9bf7d1c6c2852d9c7017a0dc52217";
    src = fetchgit {
      url = "https://github.com/lem-project/micros";
      rev = "e1d3857400a9bf7d1c6c2852d9c7017a0dc52217";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NryjqfihHjRo4thBLmdeIaZuCNBFFWVDze55KD6nxrY=";
    };
    date = "2025-08-13";
  };
}
