#!/bin/sh

if [ -f Makefile ]; then
    make distclean
fi

rm -rf .deps
rm -rf autom4te.cache
rm -f aclocal.m4 compile config.guess config.h.in config.sub \
      configure depcomp install-sh ltmain.sh Makefile.in missing

