(defpackage :lem-sdl2/layout
  (:use #:cl)
  (:export #:shift-char))
(in-package :lem-sdl2/layout)

(defparameter *us-shift-layout*
  '((#\1 . #\!)
    (#\2 . #\@)
    (#\3 . #\#)
    (#\4 . #\$)
    (#\5 . #\%)
    (#\6 . #\^)
    (#\7 . #\&)
    (#\8 . #\*)
    (#\9 . #\()
    (#\0 . #\))
    (#\- . #\_)
    (#\= . #\+)
    (#\` . #\~)
    (#\[ . #\{)
    (#\] . #\})
    (#\\ . #\|)
    (#\; . #\:)
    (#\' . #\")
    (#\, . #\<)
    (#\. . #\>)
    (#\/ . #\?)))

(defun shift-char (char)
  (if (alpha-char-p char)
      (values (char-upcase char) t)
      (let ((elt (assoc char *us-shift-layout*)))
        (if elt
            (values (cdr elt) t)
            (values char nil)))))
