# TODO Should loop over the extension directories somehow so as not to have
# to hardcode all of this.
SBLINT = "../.qlot/bin/sblint"

default:
	make -C terminal/

clean:
	make -C terminal/ clean

lint:
	${SBLINT} asciidoc-mode/lem-asciidoc-mode.asd
	${SBLINT} asm-mode/lem-asm-mode.asd
	${SBLINT} c-mode/lem-c-mode.asd
	${SBLINT} color-preview/lem-color-preview.asd
	${SBLINT} css-mode/lem-css-mode.asd
	${SBLINT} dart-mode/lem-dart-mode.asd
	${SBLINT} documentation-mode/lem-documentation-mode.asd
	${SBLINT} dot-mode/lem-dot-mode.asd
	${SBLINT} elisp-mode/lem-elisp-mode.asd
	${SBLINT} elixir-mode/lem-elixir-mode.asd
	${SBLINT} erlang-mode/lem-erlang-mode.asd
	${SBLINT} go-mode/lem-go-mode.asd
	${SBLINT} haskell-mode/lem-haskell-mode.asd
	${SBLINT} html-mode/lem-html-mode.asd
	${SBLINT} java-mode/lem-java-mode.asd
	${SBLINT} js-mode/lem-js-mode.asd
	${SBLINT} json-mode/lem-json-mode.asd
	${SBLINT} language-client/lem-language-client.asd
	${SBLINT} language-server/lem-language-server.asd
	${SBLINT} legit/lem-legit.asd
	${SBLINT} lisp-mode/lem-lisp-mode.asd
	${SBLINT} lisp-syntax/lem-lisp-syntax.asd
	${SBLINT} lsp-base/lem-lsp-base.asd
	${SBLINT} lsp-mode/lem-lsp-mode.asd
	${SBLINT} lua-mode/lem-lua-mode.asd
	${SBLINT} makefile-mode/lem-makefile-mode.asd
	${SBLINT} markdown-mode/lem-markdown-mode.asd
	${SBLINT} nim-mode/lem-nim-mode.asd
	${SBLINT} ocaml-mode/lem-ocaml-mode.asd
	${SBLINT} paredit-mode/lem-paredit-mode.asd
	${SBLINT} patch-mode/lem-patch-mode.asd
	${SBLINT} posix-shell-mode/lem-posix-shell-mode.asd
	${SBLINT} process/lem-process.asd
	${SBLINT} python-mode/lem-python-mode.asd
	${SBLINT} review-mode/lem-review-mode.asd
	${SBLINT} rust-mode/lem-rust-mode.asd
	${SBLINT} scala-mode/lem-scala-mode.asd
	${SBLINT} scheme-mode/lem-scheme-mode.asd
	${SBLINT} shell-mode/lem-shell-mode.asd
	${SBLINT} sql-mode/lem-sql-mode.asd
	${SBLINT} swift-mode/lem-swift-mode.asd
	${SBLINT} terminal/lem-terminal.asd
	${SBLINT} typescript-mode/lem-typescript-mode.asd
	${SBLINT} vi-mode/lem-vi-mode.asd
	${SBLINT} welcome/lem-welcome.asd
	${SBLINT} xml-mode/lem-xml-mode.asd
	${SBLINT} yaml-mode/lem-yaml-mode.asd
