FROM docker.io/fukamachi/qlot

COPY . .

RUN qlot install

EXPOSE 50000

ENTRYPOINT qlot exec sbcl --eval '(ql:quickload :lem-jsonrpc)' --eval '(lem-jsonrpc:run-websocket-server :port 50000 :hostname "0.0.0.0")' --quit
