(defpackage :lem/themes
  (:use :cl :lem))
(in-package :lem/themes)

(define-color-theme "emacs-light" ()
  (:display-background-mode :light)
  (:foreground "#000000")
  (:background "#FFFFFF")
  (:inactive-window-background nil)
  (region :foreground nil :background "#eedc82")
  (modeline :background "#404040" :foreground "white")
  (modeline-inactive :background "#303030" :foreground "gray")
  (syntax-string-attribute :foreground "RosyBrown")
  (syntax-comment-attribute :foreground "firebrick")
  (syntax-keyword-attribute :foreground "purple")
  (syntax-constant-attribute :foreground "#ff00ff")
  (syntax-function-name-attribute :foreground "blue")
  (syntax-variable-attribute :foreground "darkgoldenrod")
  (syntax-type-attribute :foreground "forestgreen"))

(define-color-theme "emacs-dark" ("emacs-light")
  (:display-background-mode :dark)
  (:foreground "#FFFFFF")
  (:background "#202020")
  (:inactive-window-background nil)
  (region :foreground nil :background "blue")
  (modeline :bold t :background "#404040" :foreground "white")
  (modeline-inactive :bold t :background "#292929" :foreground "#707070")
  (syntax-string-attribute :foreground "light salmon")
  (syntax-comment-attribute :foreground "chocolate1")
  (syntax-keyword-attribute :foreground "cyan1")
  (syntax-constant-attribute :foreground "LightSteelBlue")
  (syntax-function-name-attribute :foreground "LightSkyBlue")
  (syntax-variable-attribute :foreground "LightGoldenrod")
  (syntax-type-attribute :foreground "PaleGreen"))
