(in-package :lem-core)

(defvar *config-file-name* "settings.sexp")
(defvar *legacy-config-file-name* "config.lisp")

(defun lem-home ()
  (let ((xdg-lem (uiop:xdg-config-home "lem/"))
	(dot-lem (merge-pathnames ".lem/" (user-homedir-pathname))))
    (or (uiop:getenv "LEM_HOME")
	(and (probe-file dot-lem) dot-lem)
	xdg-lem)))

(defun lem-logdir-pathname ()
  (merge-pathnames "logs/" (lem-home)))

(defun config-pathname ()
  (merge-pathnames *config-file-name* (lem-home)))

(defun legacy-config-pathname ()
  (merge-pathnames *legacy-config-file-name* (lem-home)))

(defun use-legacy-config-file-p ()
  "Returns t if legacy-config-pathname exists"
  (uiop:file-exists-p (legacy-config-pathname)))

(defun ensure-config-pathname ()
  (let ((pathname (config-pathname)))
    (ensure-directories-exist pathname)
    (if (use-legacy-config-file-p)
        (legacy-config-pathname)
        pathname)))
 
(defun attempt-automigrate-config-file ()
  (let ((new-name (config-pathname))
        (old-name (legacy-config-pathname)))

    (when (and (uiop:file-exists-p old-name)
               (prompt-for-y-or-n-p (format nil "Rename legacy '~a' to '~a'?" *legacy-config-file-name* *config-file-name*)))

      ;; Redraw display is needed because otherwise the prompt doesn't disappear
      (redraw-display)

      ;; Ensure we don't overwrite any data
      (when (uiop:file-exists-p new-name)
        (with-open-file (fp new-name)
          (when (and (not (zerop (file-length fp)))
                     (not (prompt-for-y-or-n-p (format nil "~a is not an empty file, overwrite anyways?" *legacy-config-file-name*))))
            (return-from attempt-automigrate-config-file))))

      (rename-file old-name new-name))))

(defun config-plist ()
  (let ((pathname (ensure-config-pathname)))
    (if (uiop:file-exists-p pathname)
        (ignore-errors (uiop:read-file-form pathname))
        '())))

(defun config (key &optional default)
  (let ((plist (config-plist)))
    (getf plist key default)))

(defun (setf config) (value key &optional default)
  (declare (ignore default))
  (let ((plist (config-plist)))
    (if (null plist)
        (setf plist (list key value))
        (setf (getf plist key) value))
    (with-open-file (out (ensure-config-pathname)
                         :direction :output
                         :if-exists :supersede
                         :if-does-not-exist :create)
      (format out ";; THIS IS AN AUTOGENERATED FILE, DO NOT EDIT~%")
      (format out ";;~%")
      (format out ";; S-Expressions in this file are not evaluated,~%")
      (format out ";; Lisp code meant to be evalated should be put in the file `init.lisp` instead.~%")

      (pprint plist out)))
  value)
